apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-credentials
data:
  credentials: |
    [default]
    aws_access_key_id = AKIATMNWKIA5XJCCWD6Y
    aws_secret_access_key = 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
